-- =====================================================================
-- JourneyAI — feature-build schema additions (social feed, ratings,
-- saved plans, shareable links, notifications).
-- Run:  mysql -u root project < sql/features.sql   (safe to re-run)
-- Depends on: sql/migrations.sql, sql/media.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- saved_routes — already referenced by save-route.php/my-routes.php but
-- had no CREATE TABLE anywhere in the repo (it existed ad hoc in the live
-- DB). Documented here so a fresh DB setup has it.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS saved_routes (
    route_id    INT UNSIGNED NOT NULL AUTO_INCREMENT,
    eml         VARCHAR(190) NOT NULL,
    title       VARCHAR(200) NOT NULL DEFAULT 'My route',
    origin      VARCHAR(200) NULL,
    mode        VARCHAR(20)  NOT NULL DEFAULT 'day',
    data        JSON NOT NULL,
    total_km    DECIMAL(8,2) NOT NULL DEFAULT 0,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (route_id),
    KEY idx_saved_routes_eml (eml)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- saved_plans — a saved itinerary (destination + generated day-by-day
-- plan snapshot), separate from the lightweight `interactions` save
-- signal. Needed so a plan can carry a packing checklist + share token.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS saved_plans (
    plan_id      INT UNSIGNED NOT NULL AUTO_INCREMENT,
    eml          VARCHAR(190) NOT NULL,
    destination  VARCHAR(160) NOT NULL,
    days         INT NOT NULL DEFAULT 1,
    travel_style VARCHAR(40) NULL,
    month        TINYINT NULL,
    party_size   INT NOT NULL DEFAULT 1,
    itinerary    JSON NULL,             -- cached /itinerary response snapshot
    share_token  CHAR(22) NULL,         -- set when the user creates a share link
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (plan_id),
    KEY idx_saved_plans_eml (eml),
    UNIQUE KEY uq_saved_plans_token (share_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- packing_items — checklist items for a saved plan. Seeded with
-- suggested items (destination/season/duration-aware, built in PHP),
-- then freely editable (add/check/delete) by the user.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS packing_items (
    item_id    INT UNSIGNED NOT NULL AUTO_INCREMENT,
    plan_id    INT UNSIGNED NOT NULL,
    label      VARCHAR(160) NOT NULL,
    category   VARCHAR(60)  NOT NULL DEFAULT 'general',
    is_checked TINYINT(1)   NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    PRIMARY KEY (item_id),
    KEY idx_packing_plan (plan_id),
    CONSTRAINT fk_packing_plan FOREIGN KEY (plan_id) REFERENCES saved_plans(plan_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- notifications — lightweight in-app nudges shown on the dashboard
-- (e.g. "add photos to your recent trip", "your saved plan is coming up").
-- Generated by simple PHP queries (no separate worker process).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    notif_id    INT UNSIGNED NOT NULL AUTO_INCREMENT,
    eml         VARCHAR(190) NOT NULL,
    kind        VARCHAR(40)  NOT NULL,   -- e.g. 'add_photos','plan_reminder','welcome_back'
    message     VARCHAR(300) NOT NULL,
    link        VARCHAR(200) NULL,
    is_read     TINYINT(1)   NOT NULL DEFAULT 0,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (notif_id),
    KEY idx_notif_eml (eml, is_read, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- media.likes already exists (media.sql) for per-post likes; add a
-- join table so likes are per-user (toggle-able) rather than a bare
-- counter, and so "did I already like this" can be checked.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS media_likes (
    media_id   BIGINT UNSIGNED NOT NULL,
    eml        VARCHAR(190) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (media_id, eml)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- Destination ratings are derived from `interactions.rating` (already
-- collected for CF) — no new table needed. See ja-ratings.php helper
-- which aggregates AVG(rating)/COUNT(*) per destination from there.
-- ---------------------------------------------------------------------
