"""
JourneyAI — destination catalog (~100 destinations).

India-heavy (research-backed real attractions, INR daily costs, peak seasons),
plus international destinations popular with Indian travellers. Sources: budget
travel guides for India (Holidify, TravelTriangle, MakeMyTrip) and international
budget destinations for Indians (WION, Atlys, HECT) — costs are per-person/day
in INR, used as a prior for the synthetic cost generator (not ground truth).

Each destination:
    name, country, city, region, tier ('mainstream'|'lesser_known'),
    base_daily_inr, activities[], styles[], season_peak[months], attractions[]
"""

ACTIVITIES = [
    "beach", "trekking", "food", "nightlife", "history", "temples",
    "museums", "shopping", "wildlife", "adventure", "relaxation",
    "photography", "nature", "culture", "backwaters", "mountains",
    "desert", "snow", "diving", "architecture",
]

STYLES = ["budget", "mid-range", "luxury", "adventure", "family", "solo", "backpacker"]


def D(name, country, city, region, tier, base, activities, styles, peak, attractions, description=""):
    # description is optional and empty by default so none of the existing calls below need to
    # change — it's populated only where we've sourced real, cited facts from published travel
    # writing (see docs/ for sourcing), not written from scratch. Downstream consumers must treat
    # an empty description as "none available", not as an error.
    return {"name": name, "country": country, "city": city, "region": region,
            "tier": tier, "base_daily_inr": base, "activities": activities,
            "styles": styles, "season_peak": peak, "attractions": attractions,
            "description": description}


DESTINATIONS = [
    # ==================== INDIA — NORTH ====================
    D("Jaipur, India","India","Jaipur","North India","mainstream",2400,
      ["history","architecture","shopping","culture"],["mid-range","family","budget"],[10,11,12,1,2],
      ["Amber Fort","Hawa Mahal","City Palace","Jantar Mantar"]),
    D("Udaipur, India","India","Udaipur","North India","mainstream",3000,
      ["history","architecture","relaxation","photography"],["luxury","mid-range","family"],[9,10,11,2,3],
      ["Lake Pichola","City Palace","Jag Mandir","Sajjangarh"]),
    D("Jaisalmer, India","India","Jaisalmer","North India","mainstream",2600,
      ["desert","history","adventure","culture"],["mid-range","adventure","family"],[11,12,1,2],
      ["Jaisalmer Fort","Sam Sand Dunes","Patwon Ki Haveli","Gadisar Lake"]),
    D("Jodhpur, India","India","Jodhpur","North India","mainstream",2300,
      ["history","architecture","photography","shopping"],["mid-range","budget","family"],[10,11,12,1,2],
      ["Mehrangarh Fort","Umaid Bhawan","Jaswant Thada","Clock Tower Market"]),
    D("Pushkar, India","India","Pushkar","North India","lesser_known",1500,
      ["temples","culture","photography","shopping"],["backpacker","budget","solo"],[10,11,2,3],
      ["Pushkar Lake","Brahma Temple","Camel Fair","Savitri Temple"]),
    D("Agra, India","India","Agra","North India","mainstream",2200,
      ["history","architecture","photography"],["budget","family","mid-range"],[10,11,12,1,2],
      ["Taj Mahal","Agra Fort","Fatehpur Sikri","Mehtab Bagh"]),
    D("Varanasi, India","India","Varanasi","North India","mainstream",1600,
      ["temples","culture","history","photography"],["budget","backpacker","solo"],[10,11,12,1,2],
      ["Dashashwamedh Ghat","Kashi Vishwanath","Sarnath","Assi Ghat"]),
    D("Amritsar, India","India","Amritsar","North India","mainstream",1800,
      ["temples","food","history","culture"],["budget","family","solo"],[10,11,12,1,2,3],
      ["Golden Temple","Wagah Border","Jallianwala Bagh","Partition Museum"]),
    D("Rishikesh, India","India","Rishikesh","Himalayas","mainstream",1800,
      ["adventure","relaxation","temples","trekking"],["backpacker","budget","solo"],[2,3,4,9,10],
      ["Laxman Jhula","Triveni Ghat","Beatles Ashram","Ganga Aarti"]),
    D("Khajuraho, India","India","Khajuraho","North India","lesser_known",1400,
      ["history","architecture","temples","culture"],["budget","backpacker","mid-range"],[10,11,12,1,2],
      ["Western Group Temples","Kandariya Mahadev","Light Show","Panna Reserve"]),

    # ==================== INDIA — HIMALAYAS ====================
    D("Manali, India","India","Manali","Himalayas","mainstream",2600,
      ["mountains","snow","adventure","trekking"],["adventure","budget","family"],[3,4,5,6,12],
      ["Solang Valley","Rohtang Pass","Hadimba Temple","Old Manali"]),
    D("Shimla, India","India","Shimla","Himalayas","mainstream",2800,
      ["mountains","nature","relaxation","photography"],["family","mid-range","budget"],[3,4,5,6,12],
      ["The Ridge","Mall Road","Jakhoo Temple","Kufri"]),
    D("Leh Ladakh, India","India","Leh","Himalayas","mainstream",3200,
      ["mountains","adventure","photography","culture"],["adventure","backpacker","mid-range"],[6,7,8,9],
      ["Pangong Lake","Nubra Valley","Thiksey Monastery","Magnetic Hill"]),
    D("Spiti Valley, India","India","Spiti","Himalayas","lesser_known",2400,
      ["mountains","adventure","trekking","photography"],["adventure","backpacker"],[6,7,8,9],
      ["Key Monastery","Chandratal Lake","Kaza","Pin Valley"]),
    D("Mcleodganj, India","India","Mcleodganj","Himalayas","mainstream",1900,
      ["mountains","temples","relaxation","trekking"],["backpacker","budget","solo"],[3,4,5,6,9,10],
      ["Bhagsu Waterfall","Namgyal Monastery","Triund Trek","Dal Lake"]),
    D("Dharamshala, India","India","Dharamshala","Himalayas","mainstream",2000,
      ["mountains","culture","nature","trekking"],["mid-range","family","backpacker"],[3,4,5,6,9,10],
      ["Dalai Lama Temple","Kangra Fort","Tea Gardens","Cricket Stadium"]),
    D("Nainital, India","India","Nainital","Himalayas","mainstream",2500,
      ["mountains","nature","relaxation","family"],["family","mid-range","budget"],[3,4,5,6,10],
      ["Naini Lake","Naina Devi Temple","Snow View Point","Mall Road"]),
    D("Mussoorie, India","India","Mussoorie","Himalayas","mainstream",2600,
      ["mountains","nature","relaxation","photography"],["family","mid-range"],[3,4,5,6,9,10],
      ["Kempty Falls","Gun Hill","Camel's Back Road","Landour"]),
    D("Tirthan Valley, India","India","Tirthan","Himalayas","lesser_known",1900,
      ["nature","trekking","relaxation","adventure"],["backpacker","adventure","solo"],[4,5,6,9,10],
      ["Great Himalayan Park","Trout Fishing","Jalori Pass","Serolsar Lake"]),
    D("Chopta, India","India","Chopta","Himalayas","lesser_known",1800,
      ["trekking","mountains","nature","snow"],["adventure","backpacker"],[4,5,6,9,10],
      ["Tungnath Temple","Chandrashila","Deoria Tal","Meadows"]),
    D("Auli, India","India","Auli","Himalayas","lesser_known",2700,
      ["snow","adventure","mountains","photography"],["adventure","mid-range","family"],[12,1,2,3],
      ["Ski Slopes","Gorson Bugyal","Cable Car","Nanda Devi Views"]),
    D("Kasol, India","India","Kasol","Himalayas","lesser_known",1600,
      ["trekking","nature","relaxation","adventure"],["backpacker","solo","budget"],[3,4,5,6,9,10],
      ["Parvati River","Kheerganga Trek","Malana","Tosh Village"]),

    # ==================== INDIA — WEST ====================
    D("Goa, India","India","Goa","West India","mainstream",2800,
      ["beach","nightlife","relaxation","food"],["budget","mid-range","family","solo"],[11,12,1,2],
      ["Baga Beach","Fort Aguada","Dudhsagar Falls","Anjuna Flea Market"]),
    D("Mumbai, India","India","Mumbai","West India","mainstream",3500,
      ["food","nightlife","shopping","architecture"],["mid-range","luxury","solo"],[11,12,1,2],
      ["Gateway of India","Marine Drive","Elephanta Caves","Colaba"]),
    D("Kutch, India","India","Kutch","West India","lesser_known",2100,
      ["desert","culture","photography","shopping"],["mid-range","family"],[11,12,1,2],
      ["White Rann","Kalo Dungar","Handicraft Villages","Mandvi Beach"],
      description="The White Rann of Kutch is, geologically, a stretch of former seabed — cut off "
                  "from the Arabian Sea by an ancient shift, it now floods every monsoon and dries "
                  "into nearly 2,900 square miles of blinding white salt crust. From Kalo Dungar, "
                  "Kutch's highest point at 462 meters, the salt flat stretches to the horizon in "
                  "every direction, and during the Rann Utsav's full-moon nights the crust reflects "
                  "enough light to walk across without a torch."),
    D("Lonavala, India","India","Lonavala","West India","mainstream",2200,
      ["nature","mountains","relaxation","adventure"],["family","mid-range","budget"],[6,7,8,9,10],
      ["Bhushi Dam","Tiger's Leap","Karla Caves","Rajmachi Fort"]),
    D("Diu, India","India","Diu","West India","lesser_known",1900,
      ["beach","relaxation","history","photography"],["budget","family","solo"],[10,11,12,1,2],
      ["Nagoa Beach","Diu Fort","St Paul's Church","Naida Caves"],
      description="Diu remained a Portuguese colony until 1961 — 14 years after the rest of India "
                  "gained independence — and that history still shows: the 1535 sea-moated fort, "
                  "the baroque St Paul's Church with its Burmese-teak altar, and rare African hokka "
                  "palms brought over by Portuguese traders. As a Union Territory bordering "
                  "dry-state Gujarat, Diu's beach shacks are also some of the region's few places "
                  "to legally get a beer by the sea."),
    D("Mount Abu, India","India","Mount Abu","West India","mainstream",2100,
      ["mountains","temples","nature","relaxation"],["family","budget","mid-range"],[10,11,2,3,4],
      ["Dilwara Temples","Nakki Lake","Guru Shikhar","Sunset Point"]),
    D("Ahmedabad, India","India","Ahmedabad","West India","mainstream",2000,
      ["history","architecture","food","shopping","culture"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Sabarmati Ashram","Adalaj Stepwell","Kankaria Lake","Jama Masjid"],
      description="Ahmedabad earned its UNESCO World Heritage City status not for a single "
                  "monument but for an entire living neighborhood: the 600-year-old walled city "
                  "Ahmed Shah founded on the Sabarmati in 1411, still threaded with pols — gated "
                  "micro-communities built around shared wells and carved wooden bird feeders. At "
                  "its heart, Manek Chowk shape-shifts through the day, from vegetable market to "
                  "jewelry bazaar to a street-food carnival that only wakes up after 8pm."),
    D("Vadodara, India","India","Vadodara","West India","mainstream",1900,
      ["history","architecture","museums","food"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Laxmi Vilas Palace","Sayaji Baug","Baroda Museum","Champaner-Pavagadh"],
      description="Vadodara's Laxmi Vilas Palace isn't just a royal residence — at 700 acres it's "
                  "roughly four times the footprint of Buckingham Palace, built in 1890 by a "
                  "Maharaja who also filled the city's Baroda Museum with an Egyptian mummy and a "
                  "blue whale skeleton alongside 5th-century Akota bronzes. A short drive away, "
                  "Champaner-Pavagadh preserves an entire 16th-century capital that was sacked once "
                  "by the Mughals and never resettled."),
    D("Dwarka, India","India","Dwarka","West India","mainstream",1800,
      ["temples","culture","history"],["budget","family","mid-range"],[10,11,12,1,2],
      ["Dwarkadhish Temple","Bet Dwarka","Rukmini Devi Temple","Nageshwar Jyotirlinga"],
      description="Dwarka is one of Hinduism's four Char Dham sites, its 5-story, 72-pillared "
                  "Dwarkadhish Temple standing where the Gomti River meets the Arabian Sea — but "
                  "the more striking story is offshore. Since the 1960s, underwater archaeologists "
                  "have mapped real submerged stone structures near Bet Dwarka, giving physical "
                  "shape to the legend that Krishna's golden city sank beneath the waves."),
    D("Somnath, India","India","Somnath","West India","mainstream",1900,
      ["temples","history","relaxation"],["budget","mid-range","family"],[10,11,12,1,2],
      ["Somnath Temple","Triveni Sangam","Bhalka Tirth","Somnath Beach"],
      description="Somnath, first among Shiva's twelve Jyotirlingas, has been destroyed and "
                  "rebuilt an estimated 17 times — most infamously sacked by Mahmud of Ghazni in "
                  "1025 CE — with the current temple completed only in 1951 under Sardar "
                  "Vallabhbhai Patel's personal direction. At the shore's edge stands the "
                  "Banastambha, an arrow-shaped pillar inscribed with the claim that a straight "
                  "line south from this exact point crosses no land until Antarctica."),
    D("Palitana, India","India","Palitana","West India","lesser_known",1500,
      ["temples","trekking","culture"],["budget","backpacker","mid-range"],[10,11,12,1,2,3],
      ["Shatrunjaya Hill","Palitana Jain Temples","Adpur Palace","Kadambagiri Caves"],
      description="Palitana's Shatrunjaya Hill is Jainism's holiest ground — believed to be where "
                  "23 of the religion's 24 Tirthankaras attained liberation — and pilgrims still "
                  "climb its 3,750 stone steps barefoot, fasting completely on the way up and "
                  "down. By tradition, no one eats, drinks, or sleeps on the summit; by dusk the "
                  "nearly 900 marble temples that crown the hill are left empty until the next "
                  "day's climb begins."),
    D("Statue of Unity, India","India","Kevadia","West India","mainstream",2600,
      ["architecture","nature","history","photography"],["family","mid-range","luxury"],[10,11,12,1,2,3],
      ["Statue of Unity","Sardar Sarovar Dam","Valley of Flowers","Sardar Sarovar Museum"],
      description="At 182 meters, the Statue of Unity is the tallest statue on Earth — nearly "
                  "twice the height of the Statue of Liberty — built to honor Sardar Vallabhbhai "
                  "Patel, the man who stitched more than 565 fractured princely states into a "
                  "single India after 1947. A viewing gallery at 153 meters looks straight down on "
                  "the Sardar Sarovar Dam and the Narmada valley Patel's unification made possible "
                  "to govern as one."),
    D("Junagadh, India","India","Junagadh","West India","lesser_known",1700,
      ["history","architecture","trekking","temples"],["budget","mid-range","adventure"],[10,11,12,1,2,3],
      ["Girnar Hill","Uparkot Fort","Willingdon Dam","Mahabat Maqbara"]),
    D("Porbandar, India","India","Porbandar","West India","lesser_known",1600,
      ["history","beach","culture"],["budget","family","mid-range"],[10,11,12,1,2,3],
      ["Kirti Mandir","Sudama Setu","Chowpatty Beach","Birla Sadan"]),
    D("Patan, India","India","Patan","West India","lesser_known",1500,
      ["history","architecture","shopping"],["budget","mid-range"],[10,11,12,1,2,3],
      ["Rani ki Vav","Sahastralinga Talav","Patola Silk Weaving Centre","Patan Museum"]),
    D("Bhavnagar, India","India","Bhavnagar","West India","lesser_known",1600,
      ["history","culture","shopping"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Takhteshwar Temple","Nilambaug Palace","Gaurishankar Lake","Barton Museum"]),
    D("Rajkot, India","India","Rajkot","West India","mainstream",1800,
      ["history","food","shopping","culture"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Kaba Gandhi No Delo","Watson Museum","Rotary Dolls Museum","Ranchhodji Temple"]),
    D("Surat, India","India","Surat","West India","mainstream",2000,
      ["food","shopping","history","architecture"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Dutch Garden","Surat Castle","Dumas Beach","Sardar Patel Museum"]),


    # ---- auto-derived from ml/geo/local_highlights.py (88 more real Gujarat towns) ----
    D("Ambaji, India","India","Ambaji","West India","lesser_known",1500,
      ["temples","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Ambaji Temple","Gabbar Hill","Mansarovar Kund","Shaktipeeth Parikrama"]),
    D("Amreli, India","India","Amreli","West India","mainstream",1800,
      ["temples","history","nature","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Nagnath Temple","Kamnath and Trimbaknath Temples","Rajmahal Palace","Clock Tower"]),
    D("Anand, India","India","Anand","West India","lesser_known",1500,
      ["culture","museums","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Amul Dairy Plant","Dr. Verghese Kurien Memorial Museum","BAPS Shri Swaminarayan Mandir","ISKCON Vallabh Vidyanagar"]),
    D("Anjar, India","India","Anjar","West India","mainstream",1800,
      ["temples","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Jesal Toral Samadhi","Madhavrai Temple","Amba Mata's Shrine","MacMurdo Bungalow"]),
    D("Ankleshwar, India","India","Ankleshwar","West India","mainstream",1800,
      ["temples","history","wildlife","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Shri Ankleshwar Tirth","Chintamani Parsvanath Temple","Swaminarayan Temple","Nilkanthdham Poicha"]),
    D("Bardoli, India","India","Bardoli","West India","mainstream",1800,
      ["history","museums","temples","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Swaraj Ashram","Sardar Patel Museum","Kedareshwar Temple","Jalaram Temple"]),
    D("Bhachau, India","India","Bhachau","West India","mainstream",1800,
      ["history","temples","nature","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Bhachau Fort","Bhachau Swaminarayan Mandir","Balaram Palace (near Bhachau)","Rann of Kutch (nearby)"]),
    D("Bharuch, India","India","Bharuch","West India","mainstream",1800,
      ["temples","history","relaxation"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Bhrigu Rishi Temple","Jama Masjid","Bharuch Fort","Kabirvad"]),
    D("Bhuj, India","India","Bhuj","West India","mainstream",1800,
      ["history","culture","shopping"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Aina Mahal","Prag Mahal","Great Rann of Kutch (White Desert)","Bhujodi Village"]),
    D("Bilimora, India","India","Bilimora","West India","mainstream",1800,
      ["temples","beach","nature","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Swaminarayan Temple","Dandi Beach","Dumas Beach","Gira Waterfall"]),
    D("Borsad, India","India","Borsad","West India","mainstream",1800,
      ["temples","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Swami Narayan Temple","Jalaram Temple","Mahakaleshwar Mahadev Temple","Historic Stepwell"]),
    D("Botad, India","India","Botad","West India","mainstream",1800,
      ["temples","wildlife","beach","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Shree Kashtabhanjan Dev Hanumanji Mandir, Salangpur","Velavadar National Park (Blackbuck National Park)","Ghogha Beach","Botad Fort"]),
    D("Cambay Khambhat, India","India","Cambay Khambhat","West India","mainstream",1800,
      ["history","temples","shopping","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Jami Mosque","Stambheshwar Mahadev Temple","Kavi Gokalnath Temple","Shree Lakshmi Narayan Mandir"]),
    D("Dabhoi, India","India","Dabhoi","West India","mainstream",1800,
      ["history","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Dabhoi Fort","Hira Bhagol (Hira Gate)","Vadodari Bhagol (Baroda Gate)","Champaner Gate and Nandod (Nand) Gate"]),
    D("Dahod, India","India","Dahod","West India","mainstream",1800,
      ["temples","history","wildlife","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Mangadh Hill","Panchkrishna Temple","Bhavka Shiva Temple","Ratanpur Bear Sanctuary"]),
    D("Deesa, India","India","Deesa","West India","mainstream",1800,
      ["history","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Hawai Pillar","Swaminarayan Temple","Jalaram Temple","Soneshwar Mahadev Temple"]),
    D("Dehgam, India","India","Dehgam","West India","mainstream",1800,
      ["temples","nature","wildlife","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Hanumanji Temple","Dholeshwar Mahadev Temple","Zanzari Waterfalls","Nal Sarovar Bird Sanctuary"]),
    D("Devgadh Baria, India","India","Devgadh Baria","West India","mainstream",1800,
      ["history","temples","nature","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Devgadh Baria Fort / Darbargadh","Rajmahal Palace","Shri Swaminarayan Mandir","Shri Ranchhodraiji Maharaj Mandir"]),
    D("Dholka, India","India","Dholka","West India","lesser_known",1500,
      ["history","temples","shopping"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Dholka Fort","Hazrat Shah Alam Dargah","Local markets"]),
    D("Dhrangadhra, India","India","Dhrangadhra","West India","mainstream",1800,
      ["history","temples","nature","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Dhrangadhra Palace","Khodiyar Mandir","Swaminarayan Temple","Bavani Lake"]),
    D("Dhrol, India","India","Dhrol","West India","lesser_known",1200,
      ["history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Dhrol Fort / Darbargadh","Bhucharmori battlefield"]),
    D("Gandhidham, India","India","Gandhidham","West India","mainstream",1800,
      ["temples","history","nature","culture"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Bhadreswar Jain Temple","Chandra Prabh Dham Teerth","Purneshwar Temple","Gandhi Samadhi"]),
    D("Gandhinagar, India","India","Gandhinagar","West India","mainstream",1800,
      ["temples","history","museums","relaxation"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Swaminarayan Akshardham","Adalaj Stepwell","Indroda Nature Park","Sarita Udyan"]),
    D("Godhra, India","India","Godhra","West India","lesser_known",1500,
      ["temples","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Ranchhodji Temple","Khodiyar Mandir","Champaner-Pavagadh Archaeological Park"]),
    D("Gondal, India","India","Gondal","West India","mainstream",1800,
      ["history","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Naulakha Palace","Riverside Palace","Orchard Palace","Shri Swaminarayan Mandir"]),
    D("Halvad, India","India","Halvad","West India","mainstream",1800,
      ["history","temples","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Halvad Fort","Ek Dandiya Mahal (wooden Royal Palace)","Swaminarayan Temple","Jain Temples at Tikar"]),
    D("Himatnagar, India","India","Himatnagar","West India","mainstream",1800,
      ["temples","history","relaxation","culture"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Bholeshwar Temple","Mahavir Swami Jain Temple","Himmat Singh Fort","Kazi ni Vavdi"]),
    D("Idar, India","India","Idar","West India","mainstream",1800,
      ["history","temples","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Idar Fort (Idariyo Gadh)","Ruthi Rani no Mahal (Angry Queen's Palace)","Zarneshwar Mahadev Temple","Shantinath Shwetambar Jain Dersar"]),
    D("Jamnagar, India","India","Jamnagar","West India","mainstream",1800,
      ["history","relaxation","temples","shopping"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Lakhota Fort","Ranmal Lake","Bala Hanuman Temple","Khambhalia Gate"]),
    D("Jasdan, India","India","Jasdan","West India","mainstream",1800,
      ["wildlife","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Hingolgadh Nature Education Sanctuary (Hingolgadh Palace)","Jalaram Temple, Hirpara","Bhutada Dada Temple","Ram Mandir"]),
    D("Jetpur, India","India","Jetpur","West India","mainstream",1800,
      ["shopping","history","temples","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Jetpur Textile Market","Jetpur City Palace","Jetpur Fort","Nilkantheshwar Temple"]),
    D("Kadi, India","India","Kadi","West India","mainstream",1800,
      ["temples","history","relaxation","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Kadi Sarangpur Hanuman Temple","Umiya Mata Temple","Oghadnath Mahadev Temple","Malhavrav Fort"]),
    D("Kalavad, India","India","Kalavad","West India","lesser_known",1500,
      ["temples","shopping"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Shitla Mataji Temple","Nava Ranuja Temple","Local handicraft and textile markets"]),
    D("Kalol, India","India","Kalol","West India","mainstream",1800,
      ["temples","history","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Ambaji Temple","Kapileshwar Mahadev Temple","Bharat Sevashram (Durga, Hanuman & Ganesh temples)","Jamiyatpura Hanumanji Temple"]),
    D("Kapadvanj, India","India","Kapadvanj","West India","lesser_known",1500,
      ["temples","history","culture"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Jain Temple (dedicated to Lord Mahavir)","Bhadrakali Temple","Ancient step wells and forts (surrounding countryside)","Kanjari village (nearby)"]),
    D("Karjan, India","India","Karjan","West India","mainstream",1800,
      ["nature","temples","shopping"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Karjan Dam","Gopinath Mahadev Temple","Shri Shankheshwar Parshwanath Jain Tirth (Anastu)","Sumeru Navkar Jain Tirth (Golden Temple)"]),
    D("Keshod, India","India","Keshod","West India","lesser_known",1200,
      ["wildlife","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Gir National Park (nearby)","Girnar Hill (nearby, ~70 km)"]),
    D("Khambhalia, India","India","Khambhalia","West India","mainstream",1800,
      ["nature","relaxation","temples","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Ghee Dam","Anand Baug","Shiru Lake & Shiva Temple","Five Historic Gates (Nagar, Salaya, Por, Dwarka, Jodhpur Gate)"]),
    D("Kheda, India","India","Kheda","West India","lesser_known",1500,
      ["history","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Kheda Fort","Swaminarayan Temple","Gandhi Ashram, Kheda","Galteshwar"]),
    D("Kheralu, India","India","Kheralu","West India","lesser_known",1500,
      ["temples","history","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Bahuchar Mata Temple","Taranga Hills (Taranga Jain Temple)","Modhera Sun Temple","Dharoi Dam"]),
    D("Kodinar, India","India","Kodinar","West India","mainstream",1800,
      ["temples","nature","relaxation","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Bapeshwar Shiva Temple","Bhalka Tirth","Mul Dwarka","Jamjir Waterfalls"]),
    D("Limbdi, India","India","Limbdi","West India","mainstream",1800,
      ["temples","history","shopping","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["BAPS Shri Swaminarayan Temple","Jain Temple (1,100 years old)","Jasma Odan Temple","Gandhi Smruti Mandir"]),
    D("Lunawada, India","India","Lunawada","West India","mainstream",1800,
      ["temples","history","nature","relaxation"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Luneshwar Mahadev Temple","Kaleshwari","Kadana Dam","Kakachiya Triveni Sangam"]),
    D("Mahuva, India","India","Mahuva","West India","mainstream",1800,
      ["beach","temples","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Mahuva Beach","Bhavani Mata Temple","Shree Swaminarayan Mandir","Nichla Mandir"]),
    D("Mandvi, India","India","Mandvi","West India","mainstream",1800,
      ["beach","history","temples","culture"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Mandvi Beach","Vijay Vilas Palace","72 Jinalaya Temple","Mandvi Shipyards"]),
    D("Mangrol, India","India","Mangrol","West India","lesser_known",1500,
      ["beach","temples","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Mangrol Beach","Ahmedpur Mandvi Beach","Damodar Kund","Uparkot Fort"]),
    D("Mansa, India","India","Mansa","West India","lesser_known",1500,
      ["history","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Mansa Stepwell","Govardhannath Havelis and Vaishnava Temples","Former Mansa State Royal Heritage"]),
    D("Mehsana, India","India","Mehsana","West India","lesser_known",1500,
      ["temples","culture","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Simandhar Swami Jain Temple","Dudhsagar Dairy","Modhera Sun Temple","Bahuchar Mata Temple, Becharaji"]),
    D("Mithapur, India","India","Mithapur","West India","mainstream",1800,
      ["nature","beach","culture","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Mithapur Lighthouse","Mithapur Beach","Mithapur Lakes","Tata Chemicals Plant"]),
    D("Modasa, India","India","Modasa","West India","mainstream",1800,
      ["temples","history","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Modeshwari Mata Temple","Baba Ramdev Temple","Khanderay Temple","Modasa Fort"]),
    D("Modhera, India","India","Modhera","West India","lesser_known",1500,
      ["history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Modhera Sun Temple","Surya Kund","Sabha Mandap"]),
    D("Morbi, India","India","Morbi","West India","mainstream",1800,
      ["temples","history","culture"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Mani Mandir","Morbi Suspension Bridge (Jhulta Pul)","Darbargadh (Old Palace)","Wellington Secretariat"]),
    D("Nadiad, India","India","Nadiad","West India","lesser_known",1500,
      ["temples","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Santram Mandir","Mai Mandir","Shri Atmasiddhishastra Rachnabhoomi","Dahilaxmi Library"]),
    D("Navsari, India","India","Navsari","West India","mainstream",1800,
      ["history","temples","museums","beach"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["J.N. Tata Birthplace","Vadi Dar-e-Meher","Bhagarsath Anjuman Atash Behram","Meherjirana Library"]),
    D("Padra, India","India","Padra","West India","mainstream",1800,
      ["temples","wildlife","nature","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Tulja Bhavani Temple","Padra Bird Sanctuary","Narmada River","Nandalay Haveli"]),
    D("Palanpur, India","India","Palanpur","West India","lesser_known",1500,
      ["history","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Balaram Palace","Kirti Stambh","Pallaviya Parshwanath Temple"]),
    D("Petlad, India","India","Petlad","West India","lesser_known",1500,
      ["temples","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Ranchhodraiji Temple","Swaminarayan Temple (Shri Swaminarayan Mandir)","Sardar Vallabhbhai Patel Statue"]),
    D("Radhanpur, India","India","Radhanpur","West India","lesser_known",1500,
      ["culture","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Vrindavan Society area","Javantri","Zazam"]),
    D("Rajpipla, India","India","Rajpipla","West India","mainstream",1800,
      ["history","wildlife","nature","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Rajvant Palace","Shoolpaneshwar Wildlife Sanctuary","Ratanmahal Sloth Bear Sanctuary","Zarwani Waterfall"]),
    D("Rajula, India","India","Rajula","West India","lesser_known",1500,
      ["temples","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Kumbhnath Sukhnath Temple","Dhatarwadi Riverside","Chachudeshwar Mahadev Temple"]),
    D("Ranavav, India","India","Ranavav","West India","lesser_known",1500,
      ["history","wildlife","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Jambavant Cave (Jambuvant ki Gufa)","Khambhalida Caves","Barda Wildlife Sanctuary","Khimeshwar Temple"]),
    D("Rapar, India","India","Rapar","West India","mainstream",1800,
      ["history","temples","nature","museums"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Bhujia Fort","Shri Ramnathji Mandir","Vraj Temple","Jain Temples of Rapar"]),
    D("Salaya, India","India","Salaya","West India","lesser_known",1200,
      ["temples","museums"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Rukmini Temple","Salaya Museum"]),
    D("Sanand, India","India","Sanand","West India","lesser_known",1500,
      ["wildlife","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Nalsarovar Bird Sanctuary","Adalaj Stepwell","Sabarmati Ashram"]),
    D("Saputara, India","India","Saputara","West India","mainstream",1800,
      ["nature","museums","shopping"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Saputara Lake","Sunrise Point","Sunset Point (Gandhi Shikhar)","Saputara Tribal Museum"]),
    D("Savarkundla, India","India","Savarkundla","West India","lesser_known",1200,
      ["temples","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["BAPS Shri Swaminarayan Mandir","Tulsi Shyam Springs"]),
    D("Sidhpur, India","India","Sidhpur","West India","lesser_known",1500,
      ["temples","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Bindu Sarovar","Rudra Mahalaya Temple","Bohra Vad","Sidhpur Stepwell"]),
    D("Sihor, India","India","Sihor","West India","mainstream",1800,
      ["history","temples","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Brahma Kund","Gautameshwar Temple and Lake","Vijay Vilas Palace","Khodiyar Mata Temple"]),
    D("Songadh, India","India","Songadh","West India","mainstream",1800,
      ["history","nature","culture","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Songadh Fort","Gira Waterfalls","Chimer Waterfall","Ukai Dam"]),
    D("Surendranagar, India","India","Surendranagar","West India","mainstream",1800,
      ["temples","nature","wildlife","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Trinetreshwar Mahadev Temple (Tarnetar)","Chotila Hill (Chamunda Mataji Temple)","Ranmal Lake","Bajana Wildlife Sanctuary"]),
    D("Talaja, India","India","Talaja","West India","lesser_known",1500,
      ["history","temples","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Talaja Buddhist Caves","Talaja Jain Tirth (Taldhwajgiri)","Khodiyar Mata Temple","Talaja Hills"]),
    D("Thangadh, India","India","Thangadh","West India","mainstream",1800,
      ["temples","history","culture","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Khodiyar Mata Temple","Thangadh Fort","Stepwell of Thangadh","Pottery and ceramics workshops"]),
    D("Tharad, India","India","Tharad","West India","lesser_known",1500,
      ["temples","culture","nature","shopping"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Shree Mota Mahaveer (Adinath) Jain Temple","Seema Darshan, Nadabet","Great Rann of Kutch (Tharad region)","Tharad Bazaar"]),
    D("Umbergaon, India","India","Umbergaon","West India","lesser_known",1500,
      ["beach","temples","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Umbergaon Beach","Shri Swaminarayan Mandir","Daman Ganga River"]),
    D("Umreth, India","India","Umreth","West India","mainstream",1800,
      ["temples","relaxation","history"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Shree Ram Mandir","Shree Giriraj Dham","Umreth Jain Temple (Shri Shankheshwar Parshwanath)","Umreth Municipal Garden"]),
    D("Una, India","India","Una","West India","lesser_known",1500,
      ["culture","wildlife","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Delwada","Gir National Park","Somnath Temple & Beach"]),
    D("Unjha, India","India","Unjha","West India","lesser_known",1500,
      ["temples","shopping"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Shree Umiya Mata Temple","Kutchhadi Dada Temple","Hanuman Mandir","Unjha APMC Spice Market"]),
    D("Upleta, India","India","Upleta","West India","mainstream",1800,
      ["temples","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Khodiyar Mata Temple","Swaminarayan Temple","Bhadrakali Temple","Triloknath Mahadev Temple"]),
    D("Vadnagar, India","India","Vadnagar","West India","mainstream",1800,
      ["history","temples","nature","museums"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Kirti Toran","Hatkeshwar Temple","Kalika Mata Temple","Sharmistha Lake / Vadnagar Lake"]),
    D("Valsad, India","India","Valsad","West India","lesser_known",1500,
      ["beach","history","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Tithal Beach","Parnera Hill (Parnera Fort)","Bilpudi Waterfalls"]),
    D("Vapi, India","India","Vapi","West India","mainstream",1800,
      ["relaxation","nature","beach","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Nakshatra Garden","G.I.D.C Garden","Vanganga Lake","Daman Ganga Riverbank"]),
    D("Veraval, India","India","Veraval","West India","mainstream",1800,
      ["temples","beach","museums","culture"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Somnath Temple","Veraval Beach","Bhalka Tirth","Triveni Sangam"]),
    D("Vijapur, India","India","Vijapur","West India","lesser_known",1500,
      ["history","temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Vijapur Fort","Buddhisagar Suri Samadhi","Swaminarayan Temple, Vijapur","Jasmalnathji Mahadev Temple"]),
    D("Viramgam, India","India","Viramgam","West India","lesser_known",1500,
      ["history","nature","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Viramgam Fort","Town Lakes (three lakes surrounding Viramgam)","Nal Sarovar Bird Sanctuary (nearby)","Lothal (nearby)"]),
    D("Visnagar, India","India","Visnagar","West India","lesser_known",1200,
      ["temples"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Swaminarayan Temple"]),
    D("Vyara, India","India","Vyara","West India","mainstream",1800,
      ["history","temples","relaxation","nature"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Vyara Fort","Shri Swaminarayan Mandir","Jalvatika Garden","Mayadevi Waterfall Temple"]),
    D("Wadhwan, India","India","Wadhwan","West India","mainstream",1800,
      ["temples","history","wildlife"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Ranakdevi Temple","Wagheshwari Devi Temple","Madhu Vav","Ganga Vav"]),
    D("Wankaner, India","India","Wankaner","West India","mainstream",1800,
      ["history","temples","nature","culture"],["budget","mid-range","family"],[10,11,12,1,2,3],
      ["Ranjit Vilas Palace","Swaminarayan Temple","Gayatri Temple","Hazrat Shah Bava Dargah"]),

    # ==================== INDIA — SOUTH ====================
    D("Munnar, India","India","Munnar","South India","mainstream",2500,
      ["nature","trekking","relaxation","photography"],["mid-range","family","budget"],[9,10,11,12,1],
      ["Tea Gardens","Eravikulam Park","Mattupetty Dam","Top Station"]),
    D("Alleppey, India","India","Alleppey","South India","mainstream",3000,
      ["backwaters","relaxation","nature","food"],["mid-range","luxury","family"],[9,10,11,12,1,2],
      ["Houseboat Cruise","Alappuzha Beach","Backwater Villages","Kumarakom"]),
    D("Kochi, India","India","Kochi","South India","mainstream",2600,
      ["history","culture","food","architecture"],["mid-range","family","solo"],[10,11,12,1,2],
      ["Fort Kochi","Chinese Fishing Nets","Mattancherry Palace","Jew Town"]),
    D("Wayanad, India","India","Wayanad","South India","lesser_known",2200,
      ["nature","wildlife","trekking","relaxation"],["mid-range","family","adventure"],[10,11,12,1,2],
      ["Edakkal Caves","Chembra Peak","Banasura Dam","Wildlife Sanctuary"]),
    D("Varkala, India","India","Varkala","South India","lesser_known",2000,
      ["beach","relaxation","temples","nightlife"],["backpacker","budget","solo"],[10,11,12,1,2],
      ["Varkala Cliff","Papanasam Beach","Janardanaswamy Temple","Kappil Lake"]),
    D("Gokarna, India","India","Gokarna","South India","lesser_known",1700,
      ["beach","relaxation","temples","trekking"],["backpacker","budget","solo"],[11,12,1,2],
      ["Om Beach","Kudle Beach","Mahabaleshwar Temple","Half Moon Beach"]),
    D("Hampi, India","India","Hampi","South India","mainstream",1200,
      ["history","architecture","photography","culture"],["backpacker","budget","solo"],[10,11,12,1,2],
      ["Virupaksha Temple","Vittala Temple","Hemakuta Hill","Matanga Hill"]),
    D("Coorg, India","India","Coorg","South India","mainstream",2600,
      ["nature","trekking","relaxation","wildlife"],["family","mid-range","adventure"],[10,11,12,1,2,3],
      ["Abbey Falls","Raja's Seat","Dubare Elephant Camp","Coffee Estates"]),
    D("Ooty, India","India","Ooty","South India","mainstream",2400,
      ["nature","mountains","relaxation","family"],["family","mid-range","budget"],[4,5,6,9,10],
      ["Botanical Gardens","Nilgiri Toy Train","Ooty Lake","Doddabetta Peak"]),
    D("Chikmagalur, India","India","Chikmagalur","South India","lesser_known",1900,
      ["nature","trekking","relaxation","photography"],["mid-range","family","budget"],[9,10,11,12,1],
      ["Mullayanagiri","Baba Budangiri","Hebbe Falls","Coffee Estates"]),
    D("Pondicherry, India","India","Pondicherry","South India","mainstream",2300,
      ["beach","culture","food","relaxation"],["mid-range","family","solo"],[10,11,12,1,2,3],
      ["Promenade Beach","Auroville","French Quarter","Paradise Beach"]),
    D("Madurai, India","India","Madurai","South India","mainstream",1700,
      ["temples","history","food","culture"],["budget","family","solo"],[10,11,12,1,2],
      ["Meenakshi Temple","Thirumalai Nayakkar","Gandhi Museum","Alagar Koil"]),
    D("Kanyakumari, India","India","Kanyakumari","South India","lesser_known",1600,
      ["beach","temples","photography","history"],["budget","family","solo"],[10,11,12,1,2],
      ["Vivekananda Rock","Thiruvalluvar Statue","Sunset Point","Kumari Amman"]),
    D("Badami, India","India","Badami","South India","lesser_known",1300,
      ["history","architecture","photography","temples"],["backpacker","budget"],[10,11,12,1,2],
      ["Cave Temples","Agastya Lake","Bhutanatha Temple","Pattadakal"]),
    D("Coonoor, India","India","Coonoor","South India","lesser_known",2100,
      ["nature","relaxation","photography","trekking"],["family","mid-range","budget"],[4,5,6,9,10],
      ["Sim's Park","Dolphin's Nose","Tea Estates","Lamb's Rock"]),

    # ==================== INDIA — EAST & CENTRAL ====================
    D("Darjeeling, India","India","Darjeeling","East India","mainstream",2300,
      ["mountains","nature","relaxation","photography"],["mid-range","family","budget"],[3,4,5,10,11],
      ["Tiger Hill","Batasia Loop","Toy Train","Tea Estates"]),
    D("Gangtok, India","India","Gangtok","East India","mainstream",2500,
      ["mountains","nature","culture","adventure"],["mid-range","family","adventure"],[3,4,5,9,10,11],
      ["Tsomgo Lake","Nathula Pass","Rumtek Monastery","MG Marg"]),
    D("Kolkata, India","India","Kolkata","East India","mainstream",2200,
      ["culture","food","history","architecture"],["budget","mid-range","solo"],[10,11,12,1,2],
      ["Victoria Memorial","Howrah Bridge","Dakshineswar","Park Street"]),
    D("Puri, India","India","Puri","East India","mainstream",1700,
      ["beach","temples","culture","food"],["budget","family","solo"],[10,11,12,1,2],
      ["Jagannath Temple","Puri Beach","Konark Sun Temple","Chilika Lake"]),
    D("Pelling, India","India","Pelling","East India","lesser_known",2100,
      ["mountains","nature","photography","relaxation"],["mid-range","backpacker","family"],[3,4,5,10,11],
      ["Kanchenjunga View","Pemayangtse Monastery","Rabdentse Ruins","Skywalk"]),
    D("Bastar, India","India","Bastar","Central India","lesser_known",1400,
      ["culture","nature","wildlife","photography"],["backpacker","adventure","solo"],[10,11,12,1,2],
      ["Chitrakote Falls","Kanger Valley","Tribal Markets","Tirathgarh Falls"]),
    D("Orchha, India","India","Orchha","Central India","lesser_known",1500,
      ["history","architecture","temples","photography"],["budget","backpacker"],[10,11,12,1,2],
      ["Orchha Fort","Ram Raja Temple","Chhatris","Betwa River"]),
    D("Pachmarhi, India","India","Pachmarhi","Central India","lesser_known",1800,
      ["nature","trekking","relaxation","photography"],["family","budget","mid-range"],[10,11,12,1,2,3],
      ["Bee Falls","Dhupgarh","Pandav Caves","Jata Shankar"]),

    # ==================== INDIA — NORTHEAST ====================
    D("Shillong, India","India","Shillong","Northeast India","mainstream",2000,
      ["nature","mountains","relaxation","culture"],["mid-range","family","backpacker"],[3,4,5,9,10,11],
      ["Elephant Falls","Umiam Lake","Shillong Peak","Ward's Lake"]),
    D("Cherrapunji, India","India","Cherrapunji","Northeast India","lesser_known",1900,
      ["nature","trekking","photography","adventure"],["adventure","backpacker","mid-range"],[9,10,11,12],
      ["Living Root Bridges","Nohkalikai Falls","Mawsmai Cave","Seven Sisters"]),
    D("Mawlynnong, India","India","Mawlynnong","Northeast India","lesser_known",1700,
      ["nature","culture","relaxation","photography"],["backpacker","solo","family"],[9,10,11,3,4],
      ["Cleanest Village","Living Root Bridge","Sky View","Balancing Rock"]),
    D("Ziro, India","India","Ziro","Northeast India","lesser_known",2000,
      ["nature","culture","trekking","photography"],["backpacker","adventure","solo"],[3,4,9,10],
      ["Ziro Valley","Talley Valley","Apatani Villages","Kile Pakho"]),
    D("Tawang, India","India","Tawang","Northeast India","lesser_known",2300,
      ["mountains","temples","nature","photography"],["adventure","mid-range"],[3,4,5,9,10],
      ["Tawang Monastery","Sela Pass","Madhuri Lake","Bumla Pass"]),
    D("Majuli, India","India","Majuli","Northeast India","lesser_known",1500,
      ["culture","nature","photography","relaxation"],["backpacker","solo","budget"],[10,11,12,1],
      ["Satras","Mishing Villages","Mask Making","River Island"]),
    D("Kaziranga, India","India","Kaziranga","Northeast India","mainstream",2400,
      ["wildlife","nature","photography","adventure"],["mid-range","family","adventure"],[11,12,1,2,3],
      ["Rhino Safari","Elephant Safari","Bird Watching","Tea Gardens"]),

    # ==================== INDIA — WILDLIFE ====================
    D("Ranthambore, India","India","Ranthambore","North India","mainstream",2800,
      ["wildlife","photography","nature","adventure"],["mid-range","family","luxury"],[10,11,12,1,2,3],
      ["Tiger Safari","Ranthambore Fort","Padam Lake","Jungle Jeep"]),
    D("Jim Corbett, India","India","Jim Corbett","Himalayas","mainstream",2700,
      ["wildlife","nature","adventure","photography"],["family","mid-range","adventure"],[11,12,1,2,3],
      ["Tiger Reserve","Jeep Safari","Corbett Falls","Garjiya Temple"]),
    D("Gir, India","India","Gir","West India","lesser_known",2500,
      ["wildlife","nature","photography","adventure"],["mid-range","family","adventure"],[12,1,2,3,4],
      ["Asiatic Lion Safari","Devaliya Park","Kankai Temple","Crocodile Park"],
      description="Gir is the only place on Earth to see wild lions outside Africa — a population "
                  "that has rebounded from fewer than 20 individuals a century ago to 891 in the "
                  "2025 census, tracked today by GPS collars and an AI system that recognizes "
                  "individual lions by their whisker patterns. Nearly half of Gir's lions now range "
                  "outside the park into villages and farmland, and wildlife biologist Yadvendradev "
                  "Jhala has warned the species still has \"all the eggs in one basket\" — one "
                  "disease outbreak away from disaster, as a 2018 distemper outbreak that killed 23 "
                  "lions showed."),

    # ==================== INTERNATIONAL — SOUTH & SE ASIA ====================
    D("Kathmandu, Nepal","Nepal","Kathmandu","Himalayas","mainstream",2000,
      ["temples","trekking","culture","history"],["backpacker","budget","adventure"],[3,4,10,11],
      ["Pashupatinath","Boudhanath","Durbar Square","Swayambhunath"]),
    D("Pokhara, Nepal","Nepal","Pokhara","Himalayas","lesser_known",1900,
      ["trekking","nature","adventure","relaxation"],["backpacker","adventure","budget"],[3,4,10,11],
      ["Phewa Lake","Sarangkot","World Peace Pagoda","Davis Falls"]),
    D("Thimphu, Bhutan","Bhutan","Thimphu","Himalayas","lesser_known",3500,
      ["culture","temples","nature","mountains"],["mid-range","luxury","adventure"],[3,4,5,9,10,11],
      ["Tiger's Nest","Buddha Dordenma","Punakha Dzong","Dochula Pass"]),
    D("Colombo, Sri Lanka","Sri Lanka","Colombo","South Asia","mainstream",2200,
      ["beach","food","history","culture"],["mid-range","family","budget"],[12,1,2,3],
      ["Galle Face","Gangaramaya Temple","Pettah Market","National Museum"]),
    D("Ella, Sri Lanka","Sri Lanka","Ella","South Asia","lesser_known",2000,
      ["nature","trekking","relaxation","photography"],["backpacker","budget","solo"],[1,2,3,7,8],
      ["Nine Arch Bridge","Little Adam's Peak","Ella Rock","Ravana Falls"]),
    D("Bangkok, Thailand","Thailand","Bangkok","Southeast Asia","mainstream",3000,
      ["food","nightlife","shopping","temples"],["budget","mid-range","solo"],[11,12,1,2],
      ["Grand Palace","Wat Arun","Chatuchak Market","Khao San Road"]),
    D("Phuket, Thailand","Thailand","Phuket","Southeast Asia","mainstream",3600,
      ["beach","diving","nightlife","relaxation"],["mid-range","family","luxury"],[11,12,1,2,3],
      ["Patong Beach","Phi Phi Islands","Big Buddha","Old Town"]),
    D("Chiang Mai, Thailand","Thailand","Chiang Mai","Southeast Asia","lesser_known",2500,
      ["culture","temples","nature","food"],["backpacker","budget","solo"],[11,12,1,2],
      ["Doi Suthep","Old City Temples","Night Bazaar","Elephant Sanctuary"]),
    D("Bali, Indonesia","Indonesia","Bali","Southeast Asia","mainstream",3200,
      ["beach","relaxation","diving","nightlife"],["mid-range","luxury","family","solo"],[4,5,6,7,8,9],
      ["Uluwatu Temple","Ubud Rice Terraces","Seminyak","Nusa Penida"]),
    D("Hanoi, Vietnam","Vietnam","Hanoi","Southeast Asia","mainstream",2400,
      ["culture","food","history","architecture"],["backpacker","budget","solo"],[10,11,3,4],
      ["Old Quarter","Hoan Kiem Lake","Ha Long Bay","Temple of Literature"]),
    D("Hoi An, Vietnam","Vietnam","Hoi An","Southeast Asia","lesser_known",2300,
      ["culture","food","history","photography"],["mid-range","budget","family"],[2,3,4,5],
      ["Ancient Town","Japanese Bridge","An Bang Beach","Lantern Market"]),
    D("Singapore, Singapore","Singapore","Singapore","Southeast Asia","mainstream",7000,
      ["shopping","food","architecture","family"],["luxury","family","mid-range"],[2,3,4,7,8],
      ["Marina Bay Sands","Gardens by the Bay","Sentosa","Universal Studios"]),
    D("Kuala Lumpur, Malaysia","Malaysia","Kuala Lumpur","Southeast Asia","mainstream",3000,
      ["shopping","food","architecture","nightlife"],["mid-range","family","budget"],[5,6,7,12,1,2],
      ["Petronas Towers","Batu Caves","Bukit Bintang","KL Tower"]),
    D("Siem Reap, Cambodia","Cambodia","Siem Reap","Southeast Asia","lesser_known",2600,
      ["history","temples","architecture","culture"],["backpacker","budget","mid-range"],[11,12,1,2],
      ["Angkor Wat","Bayon","Ta Prohm","Tonle Sap"]),
    D("Luang Prabang, Laos","Laos","Luang Prabang","Southeast Asia","lesser_known",2500,
      ["temples","nature","relaxation","culture"],["backpacker","mid-range","solo"],[11,12,1,2],
      ["Kuang Si Falls","Mount Phousi","Night Market","Wat Xieng Thong"]),
    D("Bagan, Myanmar","Myanmar","Bagan","Southeast Asia","lesser_known",2400,
      ["history","temples","photography","culture"],["backpacker","mid-range"],[11,12,1,2],
      ["Ananda Temple","Shwesandaw","Dhammayangyi","Balloon Rides"]),

    # ==================== INTERNATIONAL — MIDDLE EAST & BEYOND ====================
    D("Dubai, UAE","UAE","Dubai","Middle East","mainstream",7500,
      ["shopping","adventure","architecture","desert"],["luxury","family"],[11,12,1,2,3],
      ["Burj Khalifa","Desert Safari","Dubai Mall","Palm Jumeirah"]),
    D("Abu Dhabi, UAE","UAE","Abu Dhabi","Middle East","mainstream",7000,
      ["architecture","culture","family","shopping"],["luxury","family"],[11,12,1,2,3],
      ["Sheikh Zayed Mosque","Ferrari World","Louvre Abu Dhabi","Corniche"]),
    D("Tbilisi, Georgia","Georgia","Tbilisi","Caucasus","lesser_known",3500,
      ["history","food","architecture","culture"],["backpacker","mid-range","solo"],[5,6,9,10],
      ["Old Town","Narikala Fortress","Sulphur Baths","Mtatsminda"]),
    D("Baku, Azerbaijan","Azerbaijan","Baku","Caucasus","lesser_known",4000,
      ["architecture","history","culture","shopping"],["mid-range","luxury"],[4,5,6,9,10],
      ["Flame Towers","Old City","Heydar Center","Gobustan"]),

    # ==================== INTERNATIONAL — EUROPE ====================
    D("Paris, France","France","Paris","Europe","mainstream",9500,
      ["history","museums","food","architecture"],["luxury","mid-range","family"],[4,5,6,9,10],
      ["Eiffel Tower","Louvre","Notre-Dame","Montmartre"]),
    D("Rome, Italy","Italy","Rome","Europe","mainstream",8800,
      ["history","architecture","food","museums"],["mid-range","luxury","family"],[4,5,6,9,10],
      ["Colosseum","Vatican","Trevi Fountain","Pantheon"]),
    D("Prague, Czech Republic","Czech Republic","Prague","Europe","mainstream",6500,
      ["history","architecture","nightlife","culture"],["mid-range","budget","solo"],[4,5,6,9,10],
      ["Charles Bridge","Prague Castle","Old Town Square","Astronomical Clock"]),
    D("Santorini, Greece","Greece","Santorini","Europe","mainstream",9000,
      ["beach","relaxation","photography","food"],["luxury","mid-range"],[5,6,7,8,9],
      ["Oia Sunset","Fira","Red Beach","Caldera Views"]),
    D("Lisbon, Portugal","Portugal","Lisbon","Europe","lesser_known",6000,
      ["history","food","culture","architecture"],["mid-range","budget","solo"],[4,5,6,9,10],
      ["Belem Tower","Alfama","Jeronimos","Tram 28"]),
    D("Interlaken, Switzerland","Switzerland","Interlaken","Europe","mainstream",11000,
      ["mountains","adventure","nature","snow"],["luxury","adventure","family"],[6,7,8,12,1],
      ["Jungfraujoch","Harder Kulm","Paragliding","Lake Thun"]),

    # ==================== INTERNATIONAL — EAST ASIA & OTHER ====================
    D("Tokyo, Japan","Japan","Tokyo","East Asia","mainstream",8500,
      ["food","shopping","culture","architecture"],["mid-range","luxury","solo"],[3,4,10,11],
      ["Shibuya","Senso-ji","Akihabara","Meiji Shrine"]),
    D("Bangkok Islands, Thailand","Thailand","Krabi","Southeast Asia","mainstream",3400,
      ["beach","diving","adventure","relaxation"],["mid-range","family","backpacker"],[11,12,1,2,3],
      ["Railay Beach","Four Islands","Tiger Cave Temple","Emerald Pool"]),
    D("Male, Maldives","Maldives","Male","South Asia","mainstream",12000,
      ["beach","diving","relaxation","photography"],["luxury","mid-range"],[11,12,1,2,3,4],
      ["Overwater Villas","Snorkeling","Male City","Sandbanks"]),
    D("Bali Ubud, Indonesia","Indonesia","Ubud","Southeast Asia","lesser_known",3000,
      ["nature","culture","relaxation","photography"],["backpacker","mid-range","solo"],[4,5,6,7,8,9],
      ["Monkey Forest","Tegallalang","Campuhan Ridge","Art Markets"]),
    D("Istanbul, Turkey","Turkey","Istanbul","Europe","mainstream",5500,
      ["history","architecture","food","shopping"],["mid-range","budget","family"],[4,5,6,9,10],
      ["Hagia Sophia","Blue Mosque","Grand Bazaar","Bosphorus"]),
    D("Cappadocia, Turkey","Turkey","Cappadocia","Europe","mainstream",6000,
      ["adventure","photography","nature","history"],["mid-range","luxury","adventure"],[4,5,6,9,10],
      ["Hot Air Balloons","Goreme","Underground City","Fairy Chimneys"]),
]


def _load_india_catalog():
    """Real, Wikivoyage-derived destinations (ml/scrape/build_india_dataset.py). Hand-curated entries
    above always win on a city-name clash; absent file => curated-only (nothing breaks)."""
    import json
    import os
    path = os.path.join(os.path.dirname(__file__), "..", "data", "india_catalog.json")
    if not os.path.exists(path):
        return []
    have = {d["city"].lower() for d in DESTINATIONS}
    out = []
    with open(path, encoding="utf8") as f:
        for d in json.load(f):
            if d["city"].lower() in have:
                continue
            out.append(D(d["name"], d["country"], d["city"], d["region"], d["tier"],
                         d["base_daily_inr"], d["activities"], d["styles"], d["season_peak"],
                         d["attractions"], d.get("description", "")))
    return out


_DEST_CACHE = None


def get_destinations():
    global _DEST_CACHE
    if _DEST_CACHE is None:
        _DEST_CACHE = DESTINATIONS + _load_india_catalog()
    return _DEST_CACHE


def by_name(name):
    for d in get_destinations():
        if d["name"] == name:
            return d
    return None


if __name__ == "__main__":
    total = len(DESTINATIONS)
    mainstream = sum(1 for d in DESTINATIONS if d["tier"] == "mainstream")
    india = sum(1 for d in DESTINATIONS if d["country"] == "India")
    costs = [d["base_daily_inr"] for d in DESTINATIONS]
    names = [d["name"] for d in DESTINATIONS]
    dupes = {n for n in names if names.count(n) > 1}
    print(f"Destinations: {total}  (mainstream={mainstream}, lesser_known={total-mainstream}, india={india}, intl={total-india})")
    print(f"Base daily INR range: {min(costs)}-{max(costs)}")
    if dupes:
        print("WARNING duplicate names:", dupes)
