"""
JourneyAI — destination catalog (~100 destinations).

India-heavy (research-backed real attractions, INR daily costs, peak seasons),
plus international destinations popular with Indian travellers. Sources: budget
travel guides for India (Holidify, TravelTriangle, MakeMyTrip) and international
budget destinations for Indians (WION, Atlys, HECT) — costs are per-person/day
in INR, used as a prior for the synthetic cost generator (not ground truth).

Each destination:
    name, country, city, region, tier ('mainstream'|'lesser_known'),
    base_daily_inr, activities[], styles[], season_peak[months], attractions[]
"""

ACTIVITIES = [
    "beach", "trekking", "food", "nightlife", "history", "temples",
    "museums", "shopping", "wildlife", "adventure", "relaxation",
    "photography", "nature", "culture", "backwaters", "mountains",
    "desert", "snow", "diving", "architecture",
]

STYLES = ["budget", "mid-range", "luxury", "adventure", "family", "solo", "backpacker"]


def D(name, country, city, region, tier, base, activities, styles, peak, attractions):
    return {"name": name, "country": country, "city": city, "region": region,
            "tier": tier, "base_daily_inr": base, "activities": activities,
            "styles": styles, "season_peak": peak, "attractions": attractions}


DESTINATIONS = [
    # ==================== INDIA — NORTH ====================
    D("Jaipur, India","India","Jaipur","North India","mainstream",2400,
      ["history","architecture","shopping","culture"],["mid-range","family","budget"],[10,11,12,1,2],
      ["Amber Fort","Hawa Mahal","City Palace","Jantar Mantar"]),
    D("Udaipur, India","India","Udaipur","North India","mainstream",3000,
      ["history","architecture","relaxation","photography"],["luxury","mid-range","family"],[9,10,11,2,3],
      ["Lake Pichola","City Palace","Jag Mandir","Sajjangarh"]),
    D("Jaisalmer, India","India","Jaisalmer","North India","mainstream",2600,
      ["desert","history","adventure","culture"],["mid-range","adventure","family"],[11,12,1,2],
      ["Jaisalmer Fort","Sam Sand Dunes","Patwon Ki Haveli","Gadisar Lake"]),
    D("Jodhpur, India","India","Jodhpur","North India","mainstream",2300,
      ["history","architecture","photography","shopping"],["mid-range","budget","family"],[10,11,12,1,2],
      ["Mehrangarh Fort","Umaid Bhawan","Jaswant Thada","Clock Tower Market"]),
    D("Pushkar, India","India","Pushkar","North India","lesser_known",1500,
      ["temples","culture","photography","shopping"],["backpacker","budget","solo"],[10,11,2,3],
      ["Pushkar Lake","Brahma Temple","Camel Fair","Savitri Temple"]),
    D("Agra, India","India","Agra","North India","mainstream",2200,
      ["history","architecture","photography"],["budget","family","mid-range"],[10,11,12,1,2],
      ["Taj Mahal","Agra Fort","Fatehpur Sikri","Mehtab Bagh"]),
    D("Varanasi, India","India","Varanasi","North India","mainstream",1600,
      ["temples","culture","history","photography"],["budget","backpacker","solo"],[10,11,12,1,2],
      ["Dashashwamedh Ghat","Kashi Vishwanath","Sarnath","Assi Ghat"]),
    D("Amritsar, India","India","Amritsar","North India","mainstream",1800,
      ["temples","food","history","culture"],["budget","family","solo"],[10,11,12,1,2,3],
      ["Golden Temple","Wagah Border","Jallianwala Bagh","Partition Museum"]),
    D("Rishikesh, India","India","Rishikesh","Himalayas","mainstream",1800,
      ["adventure","relaxation","temples","trekking"],["backpacker","budget","solo"],[2,3,4,9,10],
      ["Laxman Jhula","Triveni Ghat","Beatles Ashram","Ganga Aarti"]),
    D("Khajuraho, India","India","Khajuraho","North India","lesser_known",1400,
      ["history","architecture","temples","culture"],["budget","backpacker","mid-range"],[10,11,12,1,2],
      ["Western Group Temples","Kandariya Mahadev","Light Show","Panna Reserve"]),

    # ==================== INDIA — HIMALAYAS ====================
    D("Manali, India","India","Manali","Himalayas","mainstream",2600,
      ["mountains","snow","adventure","trekking"],["adventure","budget","family"],[3,4,5,6,12],
      ["Solang Valley","Rohtang Pass","Hadimba Temple","Old Manali"]),
    D("Shimla, India","India","Shimla","Himalayas","mainstream",2800,
      ["mountains","nature","relaxation","photography"],["family","mid-range","budget"],[3,4,5,6,12],
      ["The Ridge","Mall Road","Jakhoo Temple","Kufri"]),
    D("Leh Ladakh, India","India","Leh","Himalayas","mainstream",3200,
      ["mountains","adventure","photography","culture"],["adventure","backpacker","mid-range"],[6,7,8,9],
      ["Pangong Lake","Nubra Valley","Thiksey Monastery","Magnetic Hill"]),
    D("Spiti Valley, India","India","Spiti","Himalayas","lesser_known",2400,
      ["mountains","adventure","trekking","photography"],["adventure","backpacker"],[6,7,8,9],
      ["Key Monastery","Chandratal Lake","Kaza","Pin Valley"]),
    D("Mcleodganj, India","India","Mcleodganj","Himalayas","mainstream",1900,
      ["mountains","temples","relaxation","trekking"],["backpacker","budget","solo"],[3,4,5,6,9,10],
      ["Bhagsu Waterfall","Namgyal Monastery","Triund Trek","Dal Lake"]),
    D("Dharamshala, India","India","Dharamshala","Himalayas","mainstream",2000,
      ["mountains","culture","nature","trekking"],["mid-range","family","backpacker"],[3,4,5,6,9,10],
      ["Dalai Lama Temple","Kangra Fort","Tea Gardens","Cricket Stadium"]),
    D("Nainital, India","India","Nainital","Himalayas","mainstream",2500,
      ["mountains","nature","relaxation","family"],["family","mid-range","budget"],[3,4,5,6,10],
      ["Naini Lake","Naina Devi Temple","Snow View Point","Mall Road"]),
    D("Mussoorie, India","India","Mussoorie","Himalayas","mainstream",2600,
      ["mountains","nature","relaxation","photography"],["family","mid-range"],[3,4,5,6,9,10],
      ["Kempty Falls","Gun Hill","Camel's Back Road","Landour"]),
    D("Tirthan Valley, India","India","Tirthan","Himalayas","lesser_known",1900,
      ["nature","trekking","relaxation","adventure"],["backpacker","adventure","solo"],[4,5,6,9,10],
      ["Great Himalayan Park","Trout Fishing","Jalori Pass","Serolsar Lake"]),
    D("Chopta, India","India","Chopta","Himalayas","lesser_known",1800,
      ["trekking","mountains","nature","snow"],["adventure","backpacker"],[4,5,6,9,10],
      ["Tungnath Temple","Chandrashila","Deoria Tal","Meadows"]),
    D("Auli, India","India","Auli","Himalayas","lesser_known",2700,
      ["snow","adventure","mountains","photography"],["adventure","mid-range","family"],[12,1,2,3],
      ["Ski Slopes","Gorson Bugyal","Cable Car","Nanda Devi Views"]),
    D("Kasol, India","India","Kasol","Himalayas","lesser_known",1600,
      ["trekking","nature","relaxation","adventure"],["backpacker","solo","budget"],[3,4,5,6,9,10],
      ["Parvati River","Kheerganga Trek","Malana","Tosh Village"]),

    # ==================== INDIA — WEST ====================
    D("Goa, India","India","Goa","West India","mainstream",2800,
      ["beach","nightlife","relaxation","food"],["budget","mid-range","family","solo"],[11,12,1,2],
      ["Baga Beach","Fort Aguada","Dudhsagar Falls","Anjuna Flea Market"]),
    D("Mumbai, India","India","Mumbai","West India","mainstream",3500,
      ["food","nightlife","shopping","architecture"],["mid-range","luxury","solo"],[11,12,1,2],
      ["Gateway of India","Marine Drive","Elephanta Caves","Colaba"]),
    D("Kutch, India","India","Kutch","West India","lesser_known",2100,
      ["desert","culture","photography","shopping"],["mid-range","family"],[11,12,1,2],
      ["White Rann","Kalo Dungar","Handicraft Villages","Mandvi Beach"]),
    D("Lonavala, India","India","Lonavala","West India","mainstream",2200,
      ["nature","mountains","relaxation","adventure"],["family","mid-range","budget"],[6,7,8,9,10],
      ["Bhushi Dam","Tiger's Leap","Karla Caves","Rajmachi Fort"]),
    D("Diu, India","India","Diu","West India","lesser_known",1900,
      ["beach","relaxation","history","photography"],["budget","family","solo"],[10,11,12,1,2],
      ["Nagoa Beach","Diu Fort","St Paul's Church","Naida Caves"]),
    D("Mount Abu, India","India","Mount Abu","West India","mainstream",2100,
      ["mountains","temples","nature","relaxation"],["family","budget","mid-range"],[10,11,2,3,4],
      ["Dilwara Temples","Nakki Lake","Guru Shikhar","Sunset Point"]),

    # ==================== INDIA — SOUTH ====================
    D("Munnar, India","India","Munnar","South India","mainstream",2500,
      ["nature","trekking","relaxation","photography"],["mid-range","family","budget"],[9,10,11,12,1],
      ["Tea Gardens","Eravikulam Park","Mattupetty Dam","Top Station"]),
    D("Alleppey, India","India","Alleppey","South India","mainstream",3000,
      ["backwaters","relaxation","nature","food"],["mid-range","luxury","family"],[9,10,11,12,1,2],
      ["Houseboat Cruise","Alappuzha Beach","Backwater Villages","Kumarakom"]),
    D("Kochi, India","India","Kochi","South India","mainstream",2600,
      ["history","culture","food","architecture"],["mid-range","family","solo"],[10,11,12,1,2],
      ["Fort Kochi","Chinese Fishing Nets","Mattancherry Palace","Jew Town"]),
    D("Wayanad, India","India","Wayanad","South India","lesser_known",2200,
      ["nature","wildlife","trekking","relaxation"],["mid-range","family","adventure"],[10,11,12,1,2],
      ["Edakkal Caves","Chembra Peak","Banasura Dam","Wildlife Sanctuary"]),
    D("Varkala, India","India","Varkala","South India","lesser_known",2000,
      ["beach","relaxation","temples","nightlife"],["backpacker","budget","solo"],[10,11,12,1,2],
      ["Varkala Cliff","Papanasam Beach","Janardanaswamy Temple","Kappil Lake"]),
    D("Gokarna, India","India","Gokarna","South India","lesser_known",1700,
      ["beach","relaxation","temples","trekking"],["backpacker","budget","solo"],[11,12,1,2],
      ["Om Beach","Kudle Beach","Mahabaleshwar Temple","Half Moon Beach"]),
    D("Hampi, India","India","Hampi","South India","mainstream",1200,
      ["history","architecture","photography","culture"],["backpacker","budget","solo"],[10,11,12,1,2],
      ["Virupaksha Temple","Vittala Temple","Hemakuta Hill","Matanga Hill"]),
    D("Coorg, India","India","Coorg","South India","mainstream",2600,
      ["nature","trekking","relaxation","wildlife"],["family","mid-range","adventure"],[10,11,12,1,2,3],
      ["Abbey Falls","Raja's Seat","Dubare Elephant Camp","Coffee Estates"]),
    D("Ooty, India","India","Ooty","South India","mainstream",2400,
      ["nature","mountains","relaxation","family"],["family","mid-range","budget"],[4,5,6,9,10],
      ["Botanical Gardens","Nilgiri Toy Train","Ooty Lake","Doddabetta Peak"]),
    D("Chikmagalur, India","India","Chikmagalur","South India","lesser_known",1900,
      ["nature","trekking","relaxation","photography"],["mid-range","family","budget"],[9,10,11,12,1],
      ["Mullayanagiri","Baba Budangiri","Hebbe Falls","Coffee Estates"]),
    D("Pondicherry, India","India","Pondicherry","South India","mainstream",2300,
      ["beach","culture","food","relaxation"],["mid-range","family","solo"],[10,11,12,1,2,3],
      ["Promenade Beach","Auroville","French Quarter","Paradise Beach"]),
    D("Madurai, India","India","Madurai","South India","mainstream",1700,
      ["temples","history","food","culture"],["budget","family","solo"],[10,11,12,1,2],
      ["Meenakshi Temple","Thirumalai Nayakkar","Gandhi Museum","Alagar Koil"]),
    D("Kanyakumari, India","India","Kanyakumari","South India","lesser_known",1600,
      ["beach","temples","photography","history"],["budget","family","solo"],[10,11,12,1,2],
      ["Vivekananda Rock","Thiruvalluvar Statue","Sunset Point","Kumari Amman"]),
    D("Badami, India","India","Badami","South India","lesser_known",1300,
      ["history","architecture","photography","temples"],["backpacker","budget"],[10,11,12,1,2],
      ["Cave Temples","Agastya Lake","Bhutanatha Temple","Pattadakal"]),
    D("Coonoor, India","India","Coonoor","South India","lesser_known",2100,
      ["nature","relaxation","photography","trekking"],["family","mid-range","budget"],[4,5,6,9,10],
      ["Sim's Park","Dolphin's Nose","Tea Estates","Lamb's Rock"]),

    # ==================== INDIA — EAST & CENTRAL ====================
    D("Darjeeling, India","India","Darjeeling","East India","mainstream",2300,
      ["mountains","nature","relaxation","photography"],["mid-range","family","budget"],[3,4,5,10,11],
      ["Tiger Hill","Batasia Loop","Toy Train","Tea Estates"]),
    D("Gangtok, India","India","Gangtok","East India","mainstream",2500,
      ["mountains","nature","culture","adventure"],["mid-range","family","adventure"],[3,4,5,9,10,11],
      ["Tsomgo Lake","Nathula Pass","Rumtek Monastery","MG Marg"]),
    D("Kolkata, India","India","Kolkata","East India","mainstream",2200,
      ["culture","food","history","architecture"],["budget","mid-range","solo"],[10,11,12,1,2],
      ["Victoria Memorial","Howrah Bridge","Dakshineswar","Park Street"]),
    D("Puri, India","India","Puri","East India","mainstream",1700,
      ["beach","temples","culture","food"],["budget","family","solo"],[10,11,12,1,2],
      ["Jagannath Temple","Puri Beach","Konark Sun Temple","Chilika Lake"]),
    D("Pelling, India","India","Pelling","East India","lesser_known",2100,
      ["mountains","nature","photography","relaxation"],["mid-range","backpacker","family"],[3,4,5,10,11],
      ["Kanchenjunga View","Pemayangtse Monastery","Rabdentse Ruins","Skywalk"]),
    D("Bastar, India","India","Bastar","Central India","lesser_known",1400,
      ["culture","nature","wildlife","photography"],["backpacker","adventure","solo"],[10,11,12,1,2],
      ["Chitrakote Falls","Kanger Valley","Tribal Markets","Tirathgarh Falls"]),
    D("Orchha, India","India","Orchha","Central India","lesser_known",1500,
      ["history","architecture","temples","photography"],["budget","backpacker"],[10,11,12,1,2],
      ["Orchha Fort","Ram Raja Temple","Chhatris","Betwa River"]),
    D("Pachmarhi, India","India","Pachmarhi","Central India","lesser_known",1800,
      ["nature","trekking","relaxation","photography"],["family","budget","mid-range"],[10,11,12,1,2,3],
      ["Bee Falls","Dhupgarh","Pandav Caves","Jata Shankar"]),

    # ==================== INDIA — NORTHEAST ====================
    D("Shillong, India","India","Shillong","Northeast India","mainstream",2000,
      ["nature","mountains","relaxation","culture"],["mid-range","family","backpacker"],[3,4,5,9,10,11],
      ["Elephant Falls","Umiam Lake","Shillong Peak","Ward's Lake"]),
    D("Cherrapunji, India","India","Cherrapunji","Northeast India","lesser_known",1900,
      ["nature","trekking","photography","adventure"],["adventure","backpacker","mid-range"],[9,10,11,12],
      ["Living Root Bridges","Nohkalikai Falls","Mawsmai Cave","Seven Sisters"]),
    D("Mawlynnong, India","India","Mawlynnong","Northeast India","lesser_known",1700,
      ["nature","culture","relaxation","photography"],["backpacker","solo","family"],[9,10,11,3,4],
      ["Cleanest Village","Living Root Bridge","Sky View","Balancing Rock"]),
    D("Ziro, India","India","Ziro","Northeast India","lesser_known",2000,
      ["nature","culture","trekking","photography"],["backpacker","adventure","solo"],[3,4,9,10],
      ["Ziro Valley","Talley Valley","Apatani Villages","Kile Pakho"]),
    D("Tawang, India","India","Tawang","Northeast India","lesser_known",2300,
      ["mountains","temples","nature","photography"],["adventure","mid-range"],[3,4,5,9,10],
      ["Tawang Monastery","Sela Pass","Madhuri Lake","Bumla Pass"]),
    D("Majuli, India","India","Majuli","Northeast India","lesser_known",1500,
      ["culture","nature","photography","relaxation"],["backpacker","solo","budget"],[10,11,12,1],
      ["Satras","Mishing Villages","Mask Making","River Island"]),
    D("Kaziranga, India","India","Kaziranga","Northeast India","mainstream",2400,
      ["wildlife","nature","photography","adventure"],["mid-range","family","adventure"],[11,12,1,2,3],
      ["Rhino Safari","Elephant Safari","Bird Watching","Tea Gardens"]),

    # ==================== INDIA — WILDLIFE ====================
    D("Ranthambore, India","India","Ranthambore","North India","mainstream",2800,
      ["wildlife","photography","nature","adventure"],["mid-range","family","luxury"],[10,11,12,1,2,3],
      ["Tiger Safari","Ranthambore Fort","Padam Lake","Jungle Jeep"]),
    D("Jim Corbett, India","India","Jim Corbett","Himalayas","mainstream",2700,
      ["wildlife","nature","adventure","photography"],["family","mid-range","adventure"],[11,12,1,2,3],
      ["Tiger Reserve","Jeep Safari","Corbett Falls","Garjiya Temple"]),
    D("Gir, India","India","Gir","West India","lesser_known",2500,
      ["wildlife","nature","photography","adventure"],["mid-range","family","adventure"],[12,1,2,3,4],
      ["Asiatic Lion Safari","Devaliya Park","Kankai Temple","Crocodile Park"]),

    # ==================== INTERNATIONAL — SOUTH & SE ASIA ====================
    D("Kathmandu, Nepal","Nepal","Kathmandu","Himalayas","mainstream",2000,
      ["temples","trekking","culture","history"],["backpacker","budget","adventure"],[3,4,10,11],
      ["Pashupatinath","Boudhanath","Durbar Square","Swayambhunath"]),
    D("Pokhara, Nepal","Nepal","Pokhara","Himalayas","lesser_known",1900,
      ["trekking","nature","adventure","relaxation"],["backpacker","adventure","budget"],[3,4,10,11],
      ["Phewa Lake","Sarangkot","World Peace Pagoda","Davis Falls"]),
    D("Thimphu, Bhutan","Bhutan","Thimphu","Himalayas","lesser_known",3500,
      ["culture","temples","nature","mountains"],["mid-range","luxury","adventure"],[3,4,5,9,10,11],
      ["Tiger's Nest","Buddha Dordenma","Punakha Dzong","Dochula Pass"]),
    D("Colombo, Sri Lanka","Sri Lanka","Colombo","South Asia","mainstream",2200,
      ["beach","food","history","culture"],["mid-range","family","budget"],[12,1,2,3],
      ["Galle Face","Gangaramaya Temple","Pettah Market","National Museum"]),
    D("Ella, Sri Lanka","Sri Lanka","Ella","South Asia","lesser_known",2000,
      ["nature","trekking","relaxation","photography"],["backpacker","budget","solo"],[1,2,3,7,8],
      ["Nine Arch Bridge","Little Adam's Peak","Ella Rock","Ravana Falls"]),
    D("Bangkok, Thailand","Thailand","Bangkok","Southeast Asia","mainstream",3000,
      ["food","nightlife","shopping","temples"],["budget","mid-range","solo"],[11,12,1,2],
      ["Grand Palace","Wat Arun","Chatuchak Market","Khao San Road"]),
    D("Phuket, Thailand","Thailand","Phuket","Southeast Asia","mainstream",3600,
      ["beach","diving","nightlife","relaxation"],["mid-range","family","luxury"],[11,12,1,2,3],
      ["Patong Beach","Phi Phi Islands","Big Buddha","Old Town"]),
    D("Chiang Mai, Thailand","Thailand","Chiang Mai","Southeast Asia","lesser_known",2500,
      ["culture","temples","nature","food"],["backpacker","budget","solo"],[11,12,1,2],
      ["Doi Suthep","Old City Temples","Night Bazaar","Elephant Sanctuary"]),
    D("Bali, Indonesia","Indonesia","Bali","Southeast Asia","mainstream",3200,
      ["beach","relaxation","diving","nightlife"],["mid-range","luxury","family","solo"],[4,5,6,7,8,9],
      ["Uluwatu Temple","Ubud Rice Terraces","Seminyak","Nusa Penida"]),
    D("Hanoi, Vietnam","Vietnam","Hanoi","Southeast Asia","mainstream",2400,
      ["culture","food","history","architecture"],["backpacker","budget","solo"],[10,11,3,4],
      ["Old Quarter","Hoan Kiem Lake","Ha Long Bay","Temple of Literature"]),
    D("Hoi An, Vietnam","Vietnam","Hoi An","Southeast Asia","lesser_known",2300,
      ["culture","food","history","photography"],["mid-range","budget","family"],[2,3,4,5],
      ["Ancient Town","Japanese Bridge","An Bang Beach","Lantern Market"]),
    D("Singapore, Singapore","Singapore","Singapore","Southeast Asia","mainstream",7000,
      ["shopping","food","architecture","family"],["luxury","family","mid-range"],[2,3,4,7,8],
      ["Marina Bay Sands","Gardens by the Bay","Sentosa","Universal Studios"]),
    D("Kuala Lumpur, Malaysia","Malaysia","Kuala Lumpur","Southeast Asia","mainstream",3000,
      ["shopping","food","architecture","nightlife"],["mid-range","family","budget"],[5,6,7,12,1,2],
      ["Petronas Towers","Batu Caves","Bukit Bintang","KL Tower"]),
    D("Siem Reap, Cambodia","Cambodia","Siem Reap","Southeast Asia","lesser_known",2600,
      ["history","temples","architecture","culture"],["backpacker","budget","mid-range"],[11,12,1,2],
      ["Angkor Wat","Bayon","Ta Prohm","Tonle Sap"]),
    D("Luang Prabang, Laos","Laos","Luang Prabang","Southeast Asia","lesser_known",2500,
      ["temples","nature","relaxation","culture"],["backpacker","mid-range","solo"],[11,12,1,2],
      ["Kuang Si Falls","Mount Phousi","Night Market","Wat Xieng Thong"]),
    D("Bagan, Myanmar","Myanmar","Bagan","Southeast Asia","lesser_known",2400,
      ["history","temples","photography","culture"],["backpacker","mid-range"],[11,12,1,2],
      ["Ananda Temple","Shwesandaw","Dhammayangyi","Balloon Rides"]),

    # ==================== INTERNATIONAL — MIDDLE EAST & BEYOND ====================
    D("Dubai, UAE","UAE","Dubai","Middle East","mainstream",7500,
      ["shopping","adventure","architecture","desert"],["luxury","family"],[11,12,1,2,3],
      ["Burj Khalifa","Desert Safari","Dubai Mall","Palm Jumeirah"]),
    D("Abu Dhabi, UAE","UAE","Abu Dhabi","Middle East","mainstream",7000,
      ["architecture","culture","family","shopping"],["luxury","family"],[11,12,1,2,3],
      ["Sheikh Zayed Mosque","Ferrari World","Louvre Abu Dhabi","Corniche"]),
    D("Tbilisi, Georgia","Georgia","Tbilisi","Caucasus","lesser_known",3500,
      ["history","food","architecture","culture"],["backpacker","mid-range","solo"],[5,6,9,10],
      ["Old Town","Narikala Fortress","Sulphur Baths","Mtatsminda"]),
    D("Baku, Azerbaijan","Azerbaijan","Baku","Caucasus","lesser_known",4000,
      ["architecture","history","culture","shopping"],["mid-range","luxury"],[4,5,6,9,10],
      ["Flame Towers","Old City","Heydar Center","Gobustan"]),

    # ==================== INTERNATIONAL — EUROPE ====================
    D("Paris, France","France","Paris","Europe","mainstream",9500,
      ["history","museums","food","architecture"],["luxury","mid-range","family"],[4,5,6,9,10],
      ["Eiffel Tower","Louvre","Notre-Dame","Montmartre"]),
    D("Rome, Italy","Italy","Rome","Europe","mainstream",8800,
      ["history","architecture","food","museums"],["mid-range","luxury","family"],[4,5,6,9,10],
      ["Colosseum","Vatican","Trevi Fountain","Pantheon"]),
    D("Prague, Czech Republic","Czech Republic","Prague","Europe","mainstream",6500,
      ["history","architecture","nightlife","culture"],["mid-range","budget","solo"],[4,5,6,9,10],
      ["Charles Bridge","Prague Castle","Old Town Square","Astronomical Clock"]),
    D("Santorini, Greece","Greece","Santorini","Europe","mainstream",9000,
      ["beach","relaxation","photography","food"],["luxury","mid-range"],[5,6,7,8,9],
      ["Oia Sunset","Fira","Red Beach","Caldera Views"]),
    D("Lisbon, Portugal","Portugal","Lisbon","Europe","lesser_known",6000,
      ["history","food","culture","architecture"],["mid-range","budget","solo"],[4,5,6,9,10],
      ["Belem Tower","Alfama","Jeronimos","Tram 28"]),
    D("Interlaken, Switzerland","Switzerland","Interlaken","Europe","mainstream",11000,
      ["mountains","adventure","nature","snow"],["luxury","adventure","family"],[6,7,8,12,1],
      ["Jungfraujoch","Harder Kulm","Paragliding","Lake Thun"]),

    # ==================== INTERNATIONAL — EAST ASIA & OTHER ====================
    D("Tokyo, Japan","Japan","Tokyo","East Asia","mainstream",8500,
      ["food","shopping","culture","architecture"],["mid-range","luxury","solo"],[3,4,10,11],
      ["Shibuya","Senso-ji","Akihabara","Meiji Shrine"]),
    D("Bangkok Islands, Thailand","Thailand","Krabi","Southeast Asia","mainstream",3400,
      ["beach","diving","adventure","relaxation"],["mid-range","family","backpacker"],[11,12,1,2,3],
      ["Railay Beach","Four Islands","Tiger Cave Temple","Emerald Pool"]),
    D("Male, Maldives","Maldives","Male","South Asia","mainstream",12000,
      ["beach","diving","relaxation","photography"],["luxury","mid-range"],[11,12,1,2,3,4],
      ["Overwater Villas","Snorkeling","Male City","Sandbanks"]),
    D("Bali Ubud, Indonesia","Indonesia","Ubud","Southeast Asia","lesser_known",3000,
      ["nature","culture","relaxation","photography"],["backpacker","mid-range","solo"],[4,5,6,7,8,9],
      ["Monkey Forest","Tegallalang","Campuhan Ridge","Art Markets"]),
    D("Istanbul, Turkey","Turkey","Istanbul","Europe","mainstream",5500,
      ["history","architecture","food","shopping"],["mid-range","budget","family"],[4,5,6,9,10],
      ["Hagia Sophia","Blue Mosque","Grand Bazaar","Bosphorus"]),
    D("Cappadocia, Turkey","Turkey","Cappadocia","Europe","mainstream",6000,
      ["adventure","photography","nature","history"],["mid-range","luxury","adventure"],[4,5,6,9,10],
      ["Hot Air Balloons","Goreme","Underground City","Fairy Chimneys"]),
]


def get_destinations():
    return DESTINATIONS


def by_name(name):
    for d in DESTINATIONS:
        if d["name"] == name:
            return d
    return None


if __name__ == "__main__":
    total = len(DESTINATIONS)
    mainstream = sum(1 for d in DESTINATIONS if d["tier"] == "mainstream")
    india = sum(1 for d in DESTINATIONS if d["country"] == "India")
    costs = [d["base_daily_inr"] for d in DESTINATIONS]
    names = [d["name"] for d in DESTINATIONS]
    dupes = {n for n in names if names.count(n) > 1}
    print(f"Destinations: {total}  (mainstream={mainstream}, lesser_known={total-mainstream}, india={india}, intl={total-india})")
    print(f"Base daily INR range: {min(costs)}-{max(costs)}")
    if dupes:
        print("WARNING duplicate names:", dupes)
